version: '3.7'
services:

networks:
  monitor-net:
    external: true
    name: monitor-net
    
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
    networks:
      - monitor-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  chrome:
    image: nuget-services.spinsport.ludologic.com/docker/spinsport/node-chrome-debug:3.141.59-zinc-gb
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - monitor-net
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports:
      - 5555:5555
    deploy:
      replicas: 20
      placement:
        constraints:
          - node.role == worker 