version: '3.7'

services:

  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
    networks:
      - my-proxy-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  browsermobproxy:
    image: raul72/browsermob-proxy
    networks:
      - my-proxy-net
    environment:
      - BMP_PORT="68080"
      - BMP_PROXY_TTL="1"
    deploy:
      placement:
        constraints:
          - node.role == manager

  chrome:
    image: mcopjan/selenium_chromenode_debug_custom:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - my-proxy-net
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports:
      - 5555:5555
    deploy:
      replicas: 20
      placement:
        constraints:
          - node.role == worker

networks:
  my-proxy-net:
    external:
      name: custom_network   